import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";

import { createArray } from 'dummy-array';

const featuredCourses = createArray({to: 5})
const purchasedCourses = createArray({to: 3})

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  console.log(hello);

  return (
    <>
      <Head>
        <title>Course app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <article>
          <h1>Your courses</h1>
          <div className="mt-5 flex gap-10 flex-wrap items-center justify-center md:justify-start">
            {purchasedCourses.map(id => {
              return (<div className="w-52 h-36 bg-emerald-500 rounded-xl text-white grid place-content-center font-medium text-xl" key={id}>
              {id}
            </div>)
            })}
          </div>
        </article>

        <article>
          <h1>Featured courses</h1>
          <div className="mt-5 flex gap-10 flex-wrap items-center justify-center md:justify-start">
            {featuredCourses.map(id => {
              return (<div className="w-52 h-36 bg-blue-500 rounded-xl text-white grid place-content-center font-medium text-xl" key={id}>
              {id}
            </div>)
            })}
          </div>
        </article>
      </main>
    </>
  );
};

export default Home;
